### ISSUE TITLE
Formatting SD Card as Internal storage causes

### ISSUE THREAD

**Issue by halljames** [Black-Seraph/android_patches_gpdwin#4]
When attempting to format an SD Card as Internal storage, an error message occurs, and then causes the SD Card to show as corrupted. Formatting as Portable storage is fine.

**Comment by Black-Seraph** [comment]
I can confirm the issue. Ironically though USB devices work fine as adoptable storage.

To add on top of that... if you format the MicroSD card through a USB card reader, and then plug it into the Win's built-in reader, it will work just fine as adoptable storage.

This makes me think that something is going wrong in the formatting process when going through the built-in reader...
